### ISSUE TITLE
Створення функцій в render

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#12]
В `content.jsx` створюються функції в середині фуннції `render`. Так краще не робити, тому ще ці функції будуть перестворюватись при кожному перерендері компоненти, а вони можеть перерендурюватись дуже часто

**Comment by Xitch89** [comment]
викорав

**Comment by Xitch89** [comment]
виконав

**Comment by Xitch89** [comment]
виконав
