### ISSUE TITLE
PropTypes в `ExampleLayouts`

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#14]
`import { PropTypes } from 'prop-types';`
Дивно що це не призводить до падіння всього додатку, але змінної PropTypes не існує в prop-types :)

```
import PropTypes from 'prop-types';
import { PropTypes } from 'prop-types';
```
Різниця між цими двома імпортами в тому, що в першому випадку ми отримаєма те що було експортовано по замовчуванню, а в другому, те що було експортовано саме з таким імʼям

**Comment by Xitch89** [comment]
виправив
