### ISSUE TITLE
Список фільтрів

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#17]
Щоб не плутатись з фільтрами та не писати кожного разу 
 ```
this.setState({
    isDateChecked: true,
    isAlphabetChecked: false,
    isLessChecked: false,
  });
```
Створи одну змінну в якій зберігай який саме фильтер активний. А також константи для кожного фильтру щоб не писати рядки кожного разу

**Comment by Xitch89** [comment]
+
