### ISSUE TITLE
document.querySelectorAll

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#24]
`if (nextIndex >= 0 && nextIndex < document.querySelectorAll('.layoutsItems').length) {`

Не привʼязуй логіку до UI
1. так як ти використовуєешь модульні стилі, то класу `layoutsItems` на справді не існує, він завивається яксь типу і імʼя змінюється після пожного білда `Content_layoutsItems__yRNTG`
2. UI має залижати від даних, а не навпаки
3. Використати `numberSortPostData` навіть простіше ніж `document.querySelectorAll(...)`

**Comment by Xitch89** [comment]
виправив
