### ISSUE TITLE
indexOf vs includes

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#26]
```
const clickedIndex = clickedCards.indexOf(post.order);
if (clickedIndex !== -1) {
```

`indexOf` - повертає індекс, а якщо елемент не знайдений то -1

`includes` - перевіряє чи є елемент в масиві чи ні. Та повертає `true` або `false`, що трохи зручніше, і більше не потрібно додаткових перевірок

```
if (clickedCards.includes(post.order)) {
```

**Comment by Xitch89** [comment]
виправив
