### ISSUE TITLE
Відступи

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#34]
<img width="847" alt="Знімок екрана 2023-04-10 о 21 08 28" src="https://user-images.githubusercontent.com/59687966/230976609-2123f7d9-c674-4fa4-b322-4a8886ef038c.png">

Так не одразу зрозуміло куди зберігаються дані з запиту, краще це тримати в одному рядку, при необхідності можна винести `https://api.openweathermap.org/data/2.5/weather?q=${city}&APPID=${API_KEY}&units=metric` в окрему зміну щоб рядок не був занадто довгим

**Comment by Xitch89** [comment]
наче виправив
