### ISSUE TITLE
Стиль в іменуванні

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#5]
<img width="186" alt="Screenshot 2023-02-20 at 13 23 33" src="https://user-images.githubusercontent.com/59687966/220106403-27b7a4d9-cb6a-4848-98e7-3a045eab6601.png">

Притиримуйся одного стилю в іменуванні. Якщо всі починаються нижнього регістру, то всі повінні починатись з нижнього регістру, без виключень

Також в імені `bottom _block` є пробіл, його краще прибрати

**Comment by Xitch89** [comment]
виправив
